name: Cleanup Releases and packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Cleanup:
    name: Delete old packages and releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java and Maven - setup settings.xml
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: github
          cache: 'maven'

      - name: Get pom informations
        id: pom-info
        run: |
          GROUP_ID=$( ./mvnw help:evaluate -Dexpression=project.groupId -q -DforceStdout )
          ARTIFACT_ID=$( ./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          echo "::set-output name=group-id::$GROUP_ID"
          echo "::set-output name=artifact-id::$ARTIFACT_ID"

      - name: Display pom informations
        run: |
          echo "groupId: ${{ steps.pom-info.outputs.group-id }}"
          echo "artifactId: ${{ steps.pom-info.outputs.artifact-id }}"

      - name: Display packages names
        run: echo "${{ steps.pom-info.outputs.group-id }}.${{ steps.pom-info.outputs.artifact-id }}"

      - name: Clean old packages - keep last 3
        uses: smartsquaregmbh/delete-old-packages@v0.3.2
        with:
          keep: 3
          names: |
            "${{ steps.pom-info.outputs.group-id }}.${{ steps.pom-info.outputs.artifact-id }}"

      - name: Clean old releases - keep last 3
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

